services:
  - type: web
    name: admin-panel
    runtime: docker
    region: singapore
    plan: free
    branch: main
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: "false"
      - key: APP_ENV
        value: production
      - key: APP_URL
        sync: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: admin-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: admin-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: admin-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: admin-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: admin-db
          property: password
      - key: FONNTE_TOKEN
        sync: false
      - key: WHATSAPP_ADMIN_NUMBER
        sync: false

databases:
  - name: admin-db
    plan: free
    databaseName: admin
    user: admin

version: "1"
